export type Locale = 'jp' | 'en';

// Dictionary of Japanese keys to English translations. The English translations were generated by
// Gemini 3
export const STRINGS: Record<string, Partial<Record<Locale, string>>> = {
  // src/index.ts
  'バージョンを表示': { en: 'Show version' },
  'ヘルプを表示': { en: 'Show help' },
  '詳細情報を表示': { en: 'Show verbose output' },
  
  // Common
  '新しいXRiftプロジェクトを作成': { en: 'Create a new XRift project' },
  'ブラウザ認証でログイン': { en: 'Log in using browser authentication' },
  'ログアウト': { en: 'Log out' },
  '現在ログインしているユーザーを表示': { en: 'Show currently logged-in user' },
  'ワールドまたはアバターをアップロード': { en: 'Upload a world or avatar' },
  
  // create.ts
  'プロジェクト名（省略時は対話式）': { en: 'Project name (interactive if omitted)' },
  'テンプレートリポジトリ（例: WebXR-JP/xrift-world-template）': { en: 'Template repository (e.g. WebXR-JP/xrift-world-template)' },
  '依存関係のインストールをスキップ': { en: 'Skip installing dependencies' },
  'カレントディレクトリに直接作成': { en: 'Create directly in current directory' },
  '対話式モードを無効化': { en: 'Disable interactive mode' },
  
  // upload.ts
  'ワールドをアップロード': { en: 'Upload world' },

  // version-check.ts
  '新しいバージョンの XRift CLI が利用可能です!': { en: 'A new version of XRift CLI is available!' },
  '現在のバージョン: ': { en: 'Current version: ' },
  '最新のバージョン: ': { en: 'Latest version: ' },
  '更新するには以下のコマンドを実行してください:': { en: 'Run the following command to update:' },
};
